export {default as Signup} from "./signup"
export {default as EnterOtpSign} from "./EnterOtpSign"
export {default as ApplicantParentSign} from "./ApplicantParentSign"
export {default as ApplicantParentSign2} from "./ApplicantParentSign2"
export {default as ApplicantParentSign3} from "./ApplicantParentSign3"
export {default as ApplicantParentSign4} from "./ApplicantParentSign4"
export {default as ApplicantParentSign5} from "./ApplicantParentSign5"